import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/ui/globals.css";
import { ThemeProvider } from "@repo/ui/components/providers/theme-provider/index";
import { Toaster } from "@repo/ui/components/ui/sonner";
import { SocketProvider } from "@/context/SocketProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "BoardX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <link rel="shortcut icon" href="/logo.svg" />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark-violet"
          themes={["light", "dark-violet"]}
          enableSystem
        >
          <Toaster closeButton />
          <SocketProvider>{children}</SocketProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
